version: '3.9'

services:
  postgres_container:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shoppinghub
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin_container:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shoppinghub
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped
  api-service:
    depends_on:
      - postgres_container
    container_name: api_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - backend
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:postgresql://localhost:5432/shoppinghub",
            "spring.datasource.username": "postgres",
            "spring.datasource.password": "root",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto": "update"
          }'
    stdin_open: true
    tty: true

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:
