server:
  port: 80

spring:
  application:
    name: shoppinghub

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppinghub
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true